### ISSUE TITLE
unexploded .war in wildfly

### ISSUE THREAD

**Issue by feldi88** [dashbuilder/dashbuilder#46]
Thanks for rewriting the whole application. It looks pretty nice.

Unfortunately, the deployment of the snapshot archives fails with wildfly. I followed the readme file (https://github.com/dashbuilder/dashbuilder/blob/master/dashbuilder-distros/src/main/wildfly8/README.md) and the deployment finishes successfully. But after Login the "Please wait" message stays forever. The log output is as follows:

    19:51:33,571 WARN  [ErraiMarshalling] (default task-7) could not locate marshaller class.
    19:51:33,572 WARN  [ErraiMarshalling] (default task-7) using dynamic marshallers. dynamic marshallers are designed for development mode testing, and ideally should not be used in production. *
    19:51:39,263 INFO  [org.uberfire.backend.server.security.adapter.WeblogicGroupsAdapter] (default task-11) Unable to find weblogic.security.Security, disabling weblogic adapter
    19:51:39,264 INFO  [org.uberfire.backend.server.security.adapter.WebSphereGroupsAdapter] (default task-11) Unable to look up UserRegistry in JNDI under key 'UserRegistry', disabling websphere adapter
    19:51:42,691 INFO  [org.uberfire.backend.server.plugin.RuntimePluginsServiceServerImpl] (default task-5) Not listing directory content for frameworks/*.js because getRealPath() is returning null. (This app is probably deployed in an unexploded .war)
    19:51:42,718 INFO  [org.uberfire.backend.server.plugin.RuntimePluginsServiceServerImpl] (default task-7) Not listing directory content for plugins/*.js because getRealPath() is returning null. (This app is probably deployed in an unexploded .war)

Is there any misstake in my deployment process or is there any information missing in the deployment readme?

Thanks for your help!

**Comment by dgutierr** [comment]
Can you provide additional details please? The WAR version you are deploying, wildfly version, OS, etc... 

As far as we know, latest nightly builds are working with no issues.

**Comment by feldi88** [comment]
Thanks for your response. Here are some more information:

OS: Debian GNU/Linux 7.9 (wheezy)
AS: wildfly-8.2.1.Final
WAR: dashbuilder-distros-0.4.0-20151014.211326-64-wildfly8.war

I started wildfly with `./standalone.sh  -b 0.0.0.0 -bmanagement 0.0.0.0 --server-config=standalone-full.xml`

Then I deployed the war with `./jboss-cli.sh --connect --command="deploy /home/feldi/dashbuilder-distros-0.4.0-20151014.211326-64-wildfly8.war"`

After adding a user as described, I can logging successfully. Afterwards, I get the following error and the loading page stays:

    10:18:04,477 WARN  [ErraiMarshalling] (default task-3) could not locate marshaller class.
    10:18:04,478 WARN  [ErraiMarshalling] (default task-3) using dynamic marshallers. dynamic marshallers are designed for development mode testing, and ideally should not be used in production. *
    10:18:18,589 INFO  [org.uberfire.backend.server.security.adapter.WeblogicGroupsAdapter] (default task-16) Unable to find weblogic.security.Security, disabling weblogic adapter
    10:18:18,590 INFO  [org.uberfire.backend.server.security.adapter.WebSphereGroupsAdapter] (default task-16) Unable to look up UserRegistry in JNDI under key 'UserRegistry', disabling websphere adapter
    10:18:21,927 INFO  [org.uberfire.backend.server.plugin.RuntimePluginsServiceServerImpl] (default task-10) Not listing directory content for frameworks/*.js because getRealPath() is returning null. (This app is probably deployed in an unexploded .war)
    10:18:21,965 INFO  [org.uberfire.backend.server.plugin.RuntimePluginsServiceServerImpl] (default task-12) Not listing directory content for plugins/*.js because getRealPath() is returning null. (This app is probably deployed in an unexploded .war)

**Comment by romartin** [comment]
It look likes that you are hitting with this issue -> https://issues.jboss.org/browse/DASHBUILDE-55. It's a client side issue, please can you provider your browser concrete version?

**Comment by romartin** [comment]
Are you using an artifact from jboss nexus repository or building locally?

**Comment by feldi88** [comment]
I downloaded the packed .war from http://dashbuilder.org/downloads/downloads_ufdashb.html
I am using Chrome Version 46.0.2490.71, but I also tested it with Mozilla Firefox 41.0.2. Both result in the same problem.

**Comment by romartin** [comment]
Any error on client side? Can you check your browser console to see if the errors are similar like the ones from https://issues.jboss.org/browse/DASHBUILDE-55?

Thanks!

**Comment by romartin** [comment]
The artifacts pushed into jboss nexus are build with all permutations.. as a workaround, you can run your build locally without all the permutations, and the generated artifact works, as I have tested in my local and it only fails when building with all permutations....

1.- git clone https://github.com/dashbuilder/dashbuilder.git
2.- cd dashbuilder
3.-  mvn clean install -DskipTests
3.- cd dashbuilder-distros
4.-  mvn clean install -DskipTests
You will have you target war artifacts into dashbuilder/dashbuilder-distros/target/

We are going to deep into this issue now, but as a workaround it probably works for you :)

**Comment by feldi88** [comment]
The browser console throws the following exception:

    21:08:31 SEVERE [AbstractCreationalContext] error initializing bean: org.dashbuilder.client.ShowcaseEntryPointd4c @ org.dashbuilder.DashbuilderShowcase-0.js:12853y4c @ org.dashbuilder.DashbuilderShowcase-0.js:11683x4c @ org.dashbuilder.DashbuilderShowcase-0.js:9821C4c @ org.dashbuilder.DashbuilderShowcase-0.js:6468tZd @ org.dashbuilder.DashbuilderShowcase-0.js:4893eFd @ org.dashbuilder.DashbuilderShowcase-0.js:4895cFd @ org.dashbuilder.DashbuilderShowcase-0.js:7100Dxg @ org.dashbuilder.DashbuilderShowcase-0.js:11823qyg @ org.dashbuilder.DashbuilderShowcase-0.js:4917hwg @ org.dashbuilder.DashbuilderShowcase-0.js:12373y3c @ org.dashbuilder.DashbuilderShowcase-0.js:12845g @ org.dashbuilder.DashbuilderShowcase-0.js:11060Icb @ org.dashbuilder.DashbuilderShowcase-0.js:6016Lcb @ org.dashbuilder.DashbuilderShowcase-0.js:11246(anonymous function) @ org.dashbuilder.DashbuilderShowcase-0.js:10522u3c @ org.dashbuilder.DashbuilderShowcase-0.js:11061(anonymous function) @ org.dashbuilder.DashbuilderShowcase-0.js:12877(anonymous function) @ VM231:1m @ org.dashbuilder.DashbuilderShowcase.nocache.js:9(anonymous function) @ org.dashbuilder.DashbuilderShowcase.nocache.js:10d @ org.dashbuilder.DashbuilderShowcase.nocache.js:6(anonymous function) @ org.dashbuilder.DashbuilderShowcase.nocache.js:7
    org.dashbuilder.DashbuilderShowcase-0.js:12373 Uncaught java.lang.RuntimeException: critical error in IOC container bootstrap: java.lang.RuntimeException: error in bean initializationhwg @ org.dashbuilder.DashbuilderShowcase-0.js:12373y3c @ org.dashbuilder.DashbuilderShowcase-0.js:12845g @ org.dashbuilder.DashbuilderShowcase-0.js:11060Icb @ org.dashbuilder.DashbuilderShowcase-0.js:6016Lcb @ org.dashbuilder.DashbuilderShowcase-0.js:11246(anonymous function) @ org.dashbuilder.DashbuilderShowcase-0.js:10522u3c @ org.dashbuilder.DashbuilderShowcase-0.js:11061(anonymous function) @ org.dashbuilder.DashbuilderShowcase-0.js:12877(anonymous function) @ VM231:1m @ org.dashbuilder.DashbuilderShowcase.nocache.js:9(anonymous function) @ org.dashbuilder.DashbuilderShowcase.nocache.js:10d @ org.dashbuilder.DashbuilderShowcase.nocache.js:6(anonymous function) @ org.dashbuilder.DashbuilderShowcase.nocache.js:7
    org.dashbuilder.DashbuilderShowcase-0.js:12086 SSE channel opened (according to the browser)
    org.dashbuilder.DashbuilderShowcase-0.js:12853 receiver 'org.uberfire.ext.plugin.service.PluginServices:RPC.listDynamicMenus::8:RespondTo:RPC' threw an exceptiond4c @ org.dashbuilder.DashbuilderShowcase-0.js:12853y4c @ org.dashbuilder.DashbuilderShowcase-0.js:11683x4c @ org.dashbuilder.DashbuilderShowcase-0.js:9821C4c @ org.dashbuilder.DashbuilderShowcase-0.js:6468tZd @ org.dashbuilder.DashbuilderShowcase-0.js:4893eFd @ org.dashbuilder.DashbuilderShowcase-0.js:4895bFd @ org.dashbuilder.DashbuilderShowcase-0.js:7174uOf @ org.dashbuilder.DashbuilderShowcase-0.js:7435kIf @ org.dashbuilder.DashbuilderShowcase-0.js:12864YHf @ org.dashbuilder.DashbuilderShowcase-0.js:10742nOf @ org.dashbuilder.DashbuilderShowcase-0.js:9486LMf @ org.dashbuilder.DashbuilderShowcase-0.js:12864(anonymous function) @ org.dashbuilder.DashbuilderShowcase-0.js:12086

It's the same exception as linked by you. I will test your workaround now.

**Comment by romartin** [comment]
Yes, it's same issue, sorry about that, we found it just a couple of days ago.. just working on it! Ok please try the workaround and give us some feedback

**Comment by feldi88** [comment]
I followed your steps, but when I deploy the new artifcat, it fails with the following exception:

    {"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"dashbuilder-0.4.0-SNAPSHOT-wildfly8.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"dashbuilder-0.4.0-SNAPSHOT-wildfly8.war\".WeldStartService: Failed to start service
        Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
    Exception 0 :
    org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.dashbuilder.backend.ApplicationScopedProducer.setup() on org.dashbuilder.backend.ApplicationScopedProducer@6538bb01
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:100)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:81)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:126)
        at org.jboss.weld.injection.producer.BeanInjectionTarget.postConstruct(BeanInjectionTarget.java:70)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:162)
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)
        at org.jboss.weld.injection.producer.AbstractMemberProducer.getReceiver(AbstractMemberProducer.java:128)
        at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:148)
        at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:183)
        at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)
        at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:840)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:370)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:381)
        at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:150)
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:98)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:78)
        at org.uberfire.backend.server.io.ConfigIOServiceProducer$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
        at org.uberfire.backend.server.cdi.SystemConfigProducer.runPostConstruct(SystemConfigProducer.java:143)
        at org.uberfire.backend.server.cdi.SystemConfigProducer.afterDeploymentValidation(SystemConfigProducer.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
        at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
        at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:133)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:107)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
        at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
        at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:439)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
        at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:93)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:98)
        ... 49 more
    Caused by: java.lang.NullPointerException
        at org.dashbuilder.backend.ApplicationScopedProducer.setup(ApplicationScopedProducer.java:61)
        ... 54 more
    "}}}}

Any suggestions?

**Comment by romartin** [comment]
I'm hitting with same issue now, first time deploy it worked fine, but after a second build this exception appears to me as well, no suggestions yet :( 

The build from master seems broken till Friday, just working on it tight now, will give you feedback as soon as possible.

**Comment by romartin** [comment]
This is the issue, I think due to an external change in UberFire implemenation -> https://issues.jboss.org/browse/DASHBUILDE-56

Trying to find out the right solution...

**Comment by romartin** [comment]
There is a fix for DASHBUILDE-56. Please update master branch and re-build again. Thanks

**Comment by feldi88** [comment]
Thanks for the fix! I could successfully build and deploy the application and everything seems to run :+1:

**Comment by romartin** [comment]
Good! Thanks for testing it :) Please keep updated on the https://issues.jboss.org/browse/DASHBUILDE-55, we hope having it fixed soon :)

**Comment by romartin** [comment]
Fixed  https://issues.jboss.org/browse/DASHBUILDE-55
